### PR TITLE
Removed Boost dependency

### PR DESCRIPTION
**Pull request by 3p3r**
- Added the standalone `ASIO` as a replacement for Boost ASIO
- Added `Catch++` as a replacement for Boost Test framework
- Removed dependency on Boost DateTime and Boost Lexical Cast

** I have not removed Boost from examples due to lack of time!

### CODE REVIEW

**Comment by jeduden** [comment]
@sepehr-laal is the plan to support both boosts asio and standalone asio ? 
The project i have has multiple networking libraries ( socket
Io and cppnet ) and uses boost.
So it makes sense to use just boosts asio. 

Also cppnet lib went from using boost.asio to standalone asio back to boost.asio ( see https://github.com/cpp-netlib/cpp-netlib/issues/629 )

**Comment by sepehr-laal** [comment]
My original plan was to stop supporting Boost (although, I can see why supporting both can be useful). I got rid of Boost altogether since it's such a pain to work with and install on non Linux platforms.

I don't really understand why cppnet went back to Boost. Going through the thread you linked, it seems like an anecdotal reason to me (to go back to Boost).

These days C++ standard library is pretty powerful. Boost is really no longer needed for simple packages.

**Comment by jeduden** [comment]
Excep for asio ;) until networking has landed in the stl

**Comment by knro** [comment]
what's the status of this? I want to use this as well without Boost.

**Comment by TheOnlyJoey** [comment]
Same, boost is a burden to work with, +1 for a native method.

**Comment by cjh1** [comment]
+1 for removing boost, any movement on this?

**Comment by ppamorim** [comment]
3 years and no feedback. This project is abandoned.

**Comment by xinthose** [comment]
@ppamorim SocketIO in general has not had an update since 2017 ([blog](https://socket.io/blog/socket-io-2-0-1-2-0-2-and-2-0-3/)).  Although @darrachequesne still makes commits for the company.

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/socket.io-client-cpp/commit/af68bf3067ab45dc6a53261284e0da9afd21b636. Sorry for the delay... Could you please ping me on issues/PR that you would like to see worked on? Thanks.

**Comment by xinthose** [comment]
3.5 years of inactivity is outside of my comfort zone for code I use in production

**Pull request closed without merging**
